apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: dogs-com-tls
  namespace: default
spec:
  secretName: dogs-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: www.dogs.com
  dnsNames:
  - www.dogs.com
  acme:
    config:
    - http01:
        ingress: helloweb
      domains:
      - www.dogs.com
